# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: antikythera.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'antikythera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from compas_pb.generated import message_pb2 as compas__pb_dot_generated_dot_message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ntikythera.proto\x12\x0e\x61ntikythera.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!compas_pb/generated/message.proto\"\x8b\x03\n\x15TaskAssignmentMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x41\n\x06inputs\x18\x03 \x03(\x0b\x32\x31.antikythera.v1.TaskAssignmentMessage.InputsEntry\x12\x13\n\x0boutput_keys\x18\x04 \x03(\t\x12\x41\n\x06params\x18\x05 \x03(\x0b\x32\x31.antikythera.v1.TaskAssignmentMessage.ParamsEntry\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\x46\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.compas_pb.data.AnyData:\x02\x38\x01\x1a\x46\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.compas_pb.data.AnyData:\x02\x38\x01\"\xc9\x02\n\x15TaskCompletionMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12(\n\x05state\x18\x02 \x01(\x0e\x32\x19.antikythera.v1.TaskState\x12\x43\n\x07outputs\x18\x03 \x03(\x0b\x32\x32.antikythera.v1.TaskCompletionMessage.OutputsEntry\x12(\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x19.antikythera.v1.TaskError\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0b\x64uration_ms\x18\x06 \x01(\x04\x1aG\n\x0cOutputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.compas_pb.data.AnyData:\x02\x38\x01\"T\n\tTaskError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12(\n\x07\x64\x65tails\x18\x03 \x01(\x0b\x32\x17.compas_pb.data.AnyData*\x9e\x01\n\tTaskState\x12\x1a\n\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n\x12TASK_STATE_PENDING\x10\x01\x12\x14\n\x10TASK_STATE_READY\x10\x02\x12\x16\n\x12TASK_STATE_RUNNING\x10\x03\x12\x18\n\x14TASK_STATE_SUCCEEDED\x10\x04\x12\x15\n\x11TASK_STATE_FAILED\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antikythera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKASSIGNMENTMESSAGE_INPUTSENTRY']._loaded_options = None
  _globals['_TASKASSIGNMENTMESSAGE_INPUTSENTRY']._serialized_options = b'8\001'
  _globals['_TASKASSIGNMENTMESSAGE_PARAMSENTRY']._loaded_options = None
  _globals['_TASKASSIGNMENTMESSAGE_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_TASKCOMPLETIONMESSAGE_OUTPUTSENTRY']._loaded_options = None
  _globals['_TASKCOMPLETIONMESSAGE_OUTPUTSENTRY']._serialized_options = b'8\001'
  _globals['_TASKSTATE']._serialized_start=922
  _globals['_TASKSTATE']._serialized_end=1080
  _globals['_TASKASSIGNMENTMESSAGE']._serialized_start=106
  _globals['_TASKASSIGNMENTMESSAGE']._serialized_end=501
  _globals['_TASKASSIGNMENTMESSAGE_INPUTSENTRY']._serialized_start=359
  _globals['_TASKASSIGNMENTMESSAGE_INPUTSENTRY']._serialized_end=429
  _globals['_TASKASSIGNMENTMESSAGE_PARAMSENTRY']._serialized_start=431
  _globals['_TASKASSIGNMENTMESSAGE_PARAMSENTRY']._serialized_end=501
  _globals['_TASKCOMPLETIONMESSAGE']._serialized_start=504
  _globals['_TASKCOMPLETIONMESSAGE']._serialized_end=833
  _globals['_TASKCOMPLETIONMESSAGE_OUTPUTSENTRY']._serialized_start=762
  _globals['_TASKCOMPLETIONMESSAGE_OUTPUTSENTRY']._serialized_end=833
  _globals['_TASKERROR']._serialized_start=835
  _globals['_TASKERROR']._serialized_end=919
# @@protoc_insertion_point(module_scope)
