name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.pull_request.labels.*.name, 'docs-only')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python: ["3.9", "3.12", "3.14"]

    steps:

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate protobuf files
        run: |
          pip install -e .[dev]
          invoke generate-proto-classes -t python

      - name: Run tests
        run: |
          invoke lint
          invoke test
